### PR TITLE
feature: add option to specify number of layer versions to keep

### PR DESCRIPTION
**Pull request by yezarela**
Hi, would like to have this feature so users can specify number of layer versions to keep. 

This feature is needed to avoid old layer versions to take up much storage which was limited by AWS. 
As stated in AWS documentation here https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html , there is hard limit of 75GB of uploaded functions + layers storage.

Would like to hear your feedback, Thank you!

Example result:
image

### CODE REVIEW

**Comment by flashcoffeedev** [comment]
@agutoli thanks for responding! sure, i've updated it to use `retainVersions`. 
please kindly check, thanks

**Comment by yezarela** [comment]
@agutoli thanks for responding! sure, i've updated it to use `retainVersions`. 
please kindly check, thanks

**Comment by brunocasado** [comment]
would be nice have this feature :)

**Comment by agutoli** [comment]
This feature was already merged.

**Pull request closed without merging**
