### PR TITLE
Fix min version validation

### PR DESCRIPTION
**Pull request by Capelinha**
We never thought that serverless would release version 2 hahaha

image

### CODE REVIEW

**Comment by agutoli** [comment]
Hi @Capelinha. That's a good fix. I really appreciate your help.

**Comment by Capelinha** [comment]
> Hi @Capelinha. That's a good fix. I really appreciate your help.

Hi, @agutoli this plugin is very important for us. We have 12 serverless projects that are failing at CI / CD. When will a new version be released at npm?

image

**Comment by agutoli** [comment]
Ohh... sorry, @Capelinha. I just pushed a new version `2.3.0`.

**Comment by Capelinha** [comment]
Thank you, you are amazing :grinning:

**Comment by agutoli** [comment]
All good, man! tks

**Pull request merged**
