### PR TITLE
bugfix: #150 remove aws-sdk from nodejs layerOptimization.cleanupPatterns

### PR DESCRIPTION
**Pull request by zmw85**

### CODE REVIEW

**Comment by OmarKhattab** [comment]
@agutoli can you ship this please

**Comment by carlosmesas-acciona** [comment]
@agutoli is there an estimated date when this may be available?

**Comment by agutoli** [comment]
Thanks for your help @zmw85 .

**Comment by mohamedgamalali** [comment]
@agutoli i'm using version 2.5.4 of serverless-layers will this update works for me?

**Comment by zmw85** [comment]
> Thanks for your help @zmw85 .

No problem, we should thank you for this making this plugin. Glad that you still taking time to maintain it.

**Pull request merged**
