### PR TITLE
Release (2.6.0)

### PR DESCRIPTION
**Pull request by agutoli**
* Utilizing the provider.layers rather than function.layers when possible closes https://github.com/agutoli/serverless-layers/issues/88 - https://github.com/agutoli/serverless-layers/pull/89
* Adding support to layers compatibleArchitectures: https://github.com/agutoli/serverless-layers/pull/94

### CODE REVIEW

**Comment by Shereef** [comment]
image


```
... ○ Created layer package /Users/shereef.marzouk/Dev/daysmart-booking/service/.serverless/daysmart-booking-service-sandbox-nodejs-default.zip (1.4 MB)
... ○ Uploading layer package...
... ○ OK...
... ○ New layer version published...
... ○ Uploading remote /Users/shereef.marzouk/Dev/daysmart-booking/service/package.json...
... ○ OK...
... ○ Adding layers...
... ✓ provider - arn:aws:lambda:us-east-1:*********:daysmart-booking-service-sandbox-nodejs-default:28
... x (Skipped) function.getServiceList - because it has no other layers
... x (Skipped) function.getSiteByBookingURL - because it has no other layers
... x (Skipped) function.getSiteByDaySmartAccountID - because it has no other layers
... x (Skipped) function.getEmployeeList - because it has no other layers
... x (Skipped) function.healthVersion - because it has no other layers
... x (Skipped) function.healthCheck - because it has no other layers
... x (Skipped) function.deleteService - because it has no other layers
... x (Skipped) function.syncService - because it has no other layers
```

I am using this now and it is working and working well. thanks so much!

**Comment by Shereef** [comment]
FYI, I am on Macbook Pro with the M1 chip and it works fine
`Darwin Shmac.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64` 

The above is my `uname -a`

I know you have some arch stuff in this PR so I thought I'd let you know.

**Comment by Shereef** [comment]
@agutoli I would really appreciate it if this was released and I didn't have to use a beta version in my app.

However, I understand if you don't have the time for it and would patiently wait.

**Review by Shereef — APPROVED** [review]

**Comment by Shereef** [comment]
Thanks!

**Comment by agutoli** [comment]
@Shereef I took some days off (vacation). Sorry about late reply.

**Comment by Shereef** [comment]
I'm happy you had vacation time
This wasn't critical so all
Just didn't want it forgotten

Thanks again!
Welcome back!

**Pull request merged**
